[package]
name = "paraspace"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
static-link-z3 = ["z3/static-link-z3"]

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_json = { version = "1.0" }
z3 = { version = "0.11.2", features = []}
structopt = { version = "0.3", default-features = false }
hprof = "0.1"
ordered-float = "3.7"