name: ContainerTest
run-name: Testing using the available container
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Checking the version on Rust,Clang and Cmake
      run: |
        clang --version
        cargo --version
        cmake --version
    - name: Building Package
      run: |
        python -m venv env
        source env/bin/activate
        pip install maturin 
        maturin develop
    - name: Testing the code
      run: |
        pip install pytest pytest-cov
        pytest testPyParaspace.py --cov