name: ContainerTest
run-name: Testing using the available container
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Container
      run: |
        docker build -t mybuild .
        docker run --rm -v $(pwd):/io mybuild publish --skip-existing --compatibility manylinux2014 -i python3.10
        