name: ContainerTest
run-name: Testing using the available container
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Building Package
      run: |
        python -m venv env
        source env/bin/activate
        pip install maturin
        pip install pytest pytest-cov 
        maturin develop
    - name: List all packages
      run: |
        source env/bin/activate
        pip list
    - name: Run code
      run: | 
        source env/bin/activate
        python testPyParaspace.py
    - name: Testing the code
      run: |
        source env/bin/activate
        pytest testPyParaspace.py --cov
