name: ContainerTest
run-name: Testing using the available container
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Checking the version on Rust,Clang and Cmake
      run: |
        clang --version
        cargo --version
        cmake --version
